-- =============================================================================
-- 04_cac_ltv.sql
-- Unit Economics Intelligence Platform
-- =============================================================================
-- PURPOSE:
--   Customer Acquisition Cost (CAC) vs Lifetime Value (LTV) analysis.
--
--   THE FUNDAMENTAL RULE:
--   A business is only sustainable if LTV > CAC.
--   The industry benchmark for on-demand services is LTV:CAC >= 3.0x
--   meaning for every ₹1 spent acquiring a customer, you should earn ₹3+.
--
--   CAC  = Total marketing spend on channel / Customers acquired via channel
--   LTV  = Total contribution margin generated by a customer over their lifetime
--
--   WHY THIS MATTERS MORE THAN REVENUE:
--   High revenue from a channel means nothing if acquisition costs exceed
--   the lifetime margin that customer generates. Paid Search may drive volume
--   but destroy value if CAC is too high relative to LTV.
--
-- RUN AGAINST: unit_economics.db (SQLite)
-- =============================================================================


-- -----------------------------------------------------------------------------
-- QUERY 1: CAC by acquisition channel
-- WHY: First-touch attribution — we assign 100% of channel spend to
--      customers who signed up via that channel. This is a simplification
--      but standard practice when multi-touch data isn't available.
--      KEY INSIGHT: Paid Search CAC is ₹309 vs Organic ₹71.
-- -----------------------------------------------------------------------------
WITH customers_by_channel AS (
    SELECT
        acquisition_channel,
        COUNT(DISTINCT customer_id) AS customers_acquired
    FROM customers
    GROUP BY acquisition_channel
),
spend_by_channel AS (
    SELECT
        channel                     AS acquisition_channel,
        ROUND(SUM(spend), 2)       AS total_spend
    FROM marketing_spend
    GROUP BY channel
)
SELECT
    c.acquisition_channel,
    c.customers_acquired,
    s.total_spend,
    ROUND(s.total_spend / NULLIF(c.customers_acquired, 0), 2) AS cac
FROM customers_by_channel c
JOIN spend_by_channel s ON c.acquisition_channel = s.acquisition_channel
ORDER BY cac DESC;


-- -----------------------------------------------------------------------------
-- QUERY 2: LTV by acquisition channel
-- WHY: LTV here = total contribution margin per customer over all observed
--      orders. We use margin not revenue because revenue without cost context
--      is misleading — a channel with high revenue but high costs could be
--      worse than a low-revenue, low-cost channel.
--      KEY INSIGHT: Organic is the only channel with positive avg LTV.
-- -----------------------------------------------------------------------------
WITH customer_lifetime AS (
    SELECT
        customer_id,
        SUM(contribution_margin)    AS lifetime_margin,
        SUM(net_revenue)            AS lifetime_revenue,
        COUNT(*)                    AS total_orders,
        MIN(order_date)             AS first_order,
        MAX(order_date)             AS last_order
    FROM unit_economics
    GROUP BY customer_id
)
SELECT
    c.acquisition_channel,
    COUNT(DISTINCT c.customer_id)               AS customers,
    ROUND(AVG(cl.lifetime_margin), 2)           AS avg_ltv,
    ROUND(MIN(cl.lifetime_margin), 2)           AS min_ltv,
    ROUND(MAX(cl.lifetime_margin), 2)           AS max_ltv,
    ROUND(AVG(cl.total_orders), 1)              AS avg_orders_per_customer,
    ROUND(AVG(cl.lifetime_revenue), 2)          AS avg_lifetime_revenue
FROM customer_lifetime cl
JOIN customers c ON cl.customer_id = c.customer_id
GROUP BY c.acquisition_channel
ORDER BY avg_ltv DESC;


-- -----------------------------------------------------------------------------
-- QUERY 3: CAC vs LTV — the headline comparison
-- WHY: This is the table executives want to see. LTV:CAC ratio tells you
--      immediately which channels are creating vs destroying value.
--      Ratio < 1.0 means you are spending more to acquire than you earn.
--      Ratio < 0   means LTV is negative — the customer costs money to serve.
--
--      BENCHMARK:
--        >= 3.0x  → Healthy (industry standard)
--        1.0–3.0x → Marginal (monitor closely)
--        < 1.0x   → Warning (acquisition is destroying value)
--        < 0.0x   → Critical (LTV is negative)
-- -----------------------------------------------------------------------------
WITH customers_by_channel AS (
    SELECT acquisition_channel, COUNT(DISTINCT customer_id) AS customers_acquired
    FROM customers GROUP BY acquisition_channel
),
spend_by_channel AS (
    SELECT channel AS acquisition_channel, ROUND(SUM(spend), 2) AS total_spend
    FROM marketing_spend GROUP BY channel
),
cac_by_channel AS (
    SELECT
        c.acquisition_channel,
        c.customers_acquired,
        s.total_spend,
        ROUND(s.total_spend / NULLIF(c.customers_acquired, 0), 2) AS cac
    FROM customers_by_channel c
    JOIN spend_by_channel s ON c.acquisition_channel = s.acquisition_channel
),
customer_lifetime AS (
    SELECT customer_id, SUM(contribution_margin) AS lifetime_margin
    FROM unit_economics GROUP BY customer_id
),
ltv_by_channel AS (
    SELECT
        c.acquisition_channel,
        ROUND(AVG(cl.lifetime_margin), 2) AS avg_ltv,
        ROUND(SUM(cl.lifetime_margin), 2) AS total_ltv
    FROM customer_lifetime cl
    JOIN customers c ON cl.customer_id = c.customer_id
    GROUP BY c.acquisition_channel
)
SELECT
    cac.acquisition_channel,
    cac.customers_acquired,
    cac.cac,
    ltv.avg_ltv,
    ROUND(ltv.avg_ltv / NULLIF(cac.cac, 0), 2)     AS ltv_to_cac_ratio,
    ltv.avg_ltv - cac.cac                           AS net_value_after_cac,
    CASE
        WHEN ltv.avg_ltv / NULLIF(cac.cac, 0) >= 3.0 THEN 'Healthy'
        WHEN ltv.avg_ltv / NULLIF(cac.cac, 0) >= 1.0 THEN 'Marginal'
        WHEN ltv.avg_ltv / NULLIF(cac.cac, 0) >= 0.0 THEN 'Warning'
        ELSE                                              'Critical'
    END                                             AS health_status
FROM cac_by_channel cac
JOIN ltv_by_channel ltv ON cac.acquisition_channel = ltv.acquisition_channel
ORDER BY ltv_to_cac_ratio DESC;


-- -----------------------------------------------------------------------------
-- QUERY 4: Monthly CAC trend — is acquisition getting more or less efficient?
-- WHY: A rising CAC trend is an early warning signal. If Paid Search CAC
--      doubles over 24 months while LTV stays flat, the channel becomes
--      unviable. This query reveals that trend.
--      KEY INSIGHT: Paid Search CAC rose ~50% from Jan 2024 to Dec 2025.
-- -----------------------------------------------------------------------------
WITH monthly_spend AS (
    SELECT
        strftime('%Y-%m', date)     AS month,
        channel,
        SUM(spend)                  AS monthly_spend
    FROM marketing_spend
    GROUP BY month, channel
),
monthly_signups AS (
    SELECT
        strftime('%Y-%m', signup_date)  AS month,
        acquisition_channel,
        COUNT(DISTINCT customer_id)     AS new_customers
    FROM customers
    GROUP BY month, acquisition_channel
)
SELECT
    ms.month,
    ms.channel                          AS acquisition_channel,
    ROUND(ms.monthly_spend, 2)         AS spend,
    COALESCE(sg.new_customers, 0)       AS new_customers,
    CASE
        WHEN COALESCE(sg.new_customers, 0) > 0
        THEN ROUND(ms.monthly_spend / sg.new_customers, 2)
        ELSE NULL
    END                                 AS monthly_cac
FROM monthly_spend ms
LEFT JOIN monthly_signups sg
    ON ms.month = sg.month
    AND ms.channel = sg.acquisition_channel
ORDER BY ms.channel, ms.month;